### ISSUE TITLE
Docker for services for easy setup & avoiding platform specific files

### ISSUE THREAD

**Issue by kcolton** [SaltieRL/DistributedReplays#69]
Setup my local environment with a docker-compose.yml file so I didn't need to worry about installing postgres, redis, rabbitmq (needed at the time). 

The docker-compose.yml file currently using
```
version: "3"
services:
  redis:
    image: redis:4-alpine
    container_name: saltie-redis4
    restart: always
    volumes:
      - "./.data/redis:/data"
    ports:
      - 6379:6379
  # Don't think this is used anymore, but using docker saves headache of installing erlang and all that
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: saltie-rabbitmq
    restart: always
    volumes:
      - "./.data/rabbitmq:/data"
    ports:
      - 5672:5672

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: postgres
```

Starting and stopping:
```
# Start service dependencies
$ docker-compose up
# Stop service dependencies
$ docker-compose down
```

Removes the needs for having most of the platform specific files that exist now. Great for local environments - optionally useful for future production deployments, but takes more consideration.

rattletrap could also be trivially be added to a docker image and ran in a container without much of a hit to total parsing performance - but thats for another issue
